In [6]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt

from pandas import Series, DataFrame
import pandas as pd

from sklearn.tree import DecisionTreeClassifier

In [7]:
data = pd.read_csv('titanic.csv', index_col='PassengerId')
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [8]:
X = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])
clf = DecisionTreeClassifier()
clf.fit(X, y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [10]:
importances = clf.feature_importances_

In [11]:
importances

array([ 1.,  0.])

In [12]:
X

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
y

array([0, 1, 0])

In [28]:
modData = data[['Pclass', 'Fare', 'Age', 'Sex', 'Survived']]

In [29]:
dropData = modData.dropna(axis='index')

In [30]:
dropData.shape

(714, 5)

In [31]:
data.shape

(891, 11)

In [64]:
cropData = dropData[['Pclass', 'Fare', 'Age', 'Sex']]
newSex = cropData['Sex'].replace('male', 1).replace('female', 0)
#del cropData['Sex']
cropData['Sex'] = newSex
cropData

C:\Program Files\Anaconda3\lib\site-packages\ipykernel\__main__.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


Pclass      Fare   Age  Sex
PassengerId                             
1                 3    7.2500  22.0    1
2                 1   71.2833  38.0    0
3                 3    7.9250  26.0    0
4                 1   53.1000  35.0    0
5                 3    8.0500  35.0    1
7                 1   51.8625  54.0    1
8                 3   21.0750   2.0    1
9                 3   11.1333  27.0    0
10                2   30.0708  14.0    0
11                3   16.7000   4.0    0
12                1   26.5500  58.0    0
13                3    8.0500  20.0    1
14                3   31.2750  39.0    1
15                3    7.8542  14.0    0
16                2   16.0000  55.0    0
17                3   29.1250   2.0    1
19                3   18.0000  31.0    0
21                2   26.0000  35.0    1
22                2   13.0000  34.0    1
23                3    8.0292  15.0    0
24                1   35.5000  28.0    1
25                3   21.0750   8.0    0
26                3   31.3875  38.0    0
28                1  263.0000  19.0    1
31                1   27.7208  40.0    1
34                2   10.5000  66.0    1
35                1   82.1708  28.0    1
36                1   52.0000  42.0    1
38                3    8.0500  21.0    1
39                3   18.0000  18.0    0
...             ...       ...   ...  ...
857               1  164.8667  45.0    0
858               1   26.5500  51.0    1
859               3   19.2583  24.0    0
861               3   14.1083  41.0    1
862               2   11.5000  21.0    1
863               1   25.9292  48.0    0
865               2   13.0000  24.0    1
866               2   13.0000  42.0    0
867               2   13.8583  27.0    0
868               1   50.4958  31.0    1
870               3   11.1333   4.0    1
871               3    7.8958  26.0    1
872               1   52.5542  47.0    0
873               1    5.0000  33.0    1
874               3    9.0000  47.0    1
875               2   24.0000  28.0    0
876               3    7.2250  15.0    0
877               3    9.8458  20.0    1
878               3    7.8958  19.0    1
880               1   83.1583  56.0    0
881               2   26.0000  25.0    0
882               3    7.8958  33.0    1
883               3   10.5167  22.0    0
884               2   10.5000  28.0    1
885               3    7.0500  25.0    1
886               3   29.1250  39.0    0
887               2   13.0000  27.0    1
888               1   30.0000  19.0    0
890               1   30.0000  26.0    1
891               3    7.7500  32.0    1

[714 rows x 4 columns]

In [65]:
targetData = dropData['Survived']

In [66]:
cropData.shape

(714, 4)

In [67]:
targetData.shape

(714,)

In [70]:
clf = DecisionTreeClassifier(random_state = 241)
clf.fit(cropData, targetData)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=241, splitter='best')

In [72]:
importances = clf.feature_importances_
importances

array([ 0.14000522,  0.30343647,  0.2560461 ,  0.30051221])